name: docs site
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: corepack enable
      - run: corepack prepare yarn@stable --activate
      - run: yarn build
      - run: yarn build:docs
concurrency:
  group: build-docs-site
  cancel-in-progress: true
on:
  push:
    branches-ignore:
      - main
