name: lint
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: corepack enable
      - run: corepack prepare yarn@stable --activate
      - run: yarn check:lint
concurrency:
  group: check-lint
  cancel-in-progress: true
on: push
