name: types
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: corepack enable
      - run: corepack prepare yarn@stable --activate
      - run: yarn run build
      - run: yarn run check:types
concurrency:
  group: check-types
  cancel-in-progress: true
on: push
